### ISSUE TITLE
Comentarios

### ISSUE THREAD

**Issue by gastonprieto** [LucasBarr99/QMP#2]
* En general esta bien encarado :)

* Si ves que no vas a poner el código, no hace falta que subas toda la estructura de un proyecto Java (src, pom.xml, etc).

* MaterialPrenda podes ponerle solo Materia, porque se deduce que es de la Prenda y te quita la posibilidad tal vez de usarlo en otro contexto.

* Podrías generar un método con la validación para un valor, para evitar esta duplicación de lógica:

[this.tipoPrenda = tipo != null ? tipo : throw new DomainException("el atributo tipo es obligatorio")](https://github.com/LucasBarr99/QMP1/blob/e6d7986b8a400b0046215886c98277cd1bf3aac3/README.md#L45-L47)

* Falta explicar como resolves el color secundario

* `colorP` es mejor `colorPrimario` :)

**Comment by LucasBarr99** [comment]
Muchas gracias por los comentarios!
